BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Reading] (
    [id] NVARCHAR(1000) NOT NULL,
    [title] NVARCHAR(1000) NOT NULL,
    [author] NVARCHAR(1000) NOT NULL,
    [link] NVARCHAR(1000) NOT NULL,
    [pubDate] NVARCHAR(1000) NOT NULL,
    [isbn] NVARCHAR(1000),
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Reading_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [Reading_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
